---
- name: Install main dependencies
  ansible.builtin.package:
    name:
      - git
      - acl
    state: present
  when: ansible_distribution == "Ubuntu" or ansible_distribution == "Debian"

- name: Create a system user for Estuary
  ansible.builtin.user:
    name: "{{ estuary_system_user | default('estuary') }}"
    shell: /bin/bash
    system: true

- name: Create estuary-www folder
  ansible.builtin.file:
    path: /usr/src/estuary-www
    owner: "{{ estuary_system_user | default('estuary') }}"
    group: "{{ estuary_system_user | default('estuary') }}"
    mode: 0700
    state: directory
    recurse: false

- name: Check out estuary-www from git
  ansible.builtin.git:
    repo: https://github.com/application-research/estuary-www
    dest: /usr/src/estuary-www
  become: true
  become_user: "{{ estuary_system_user | default('estuary') }}"

- name: Build estuary-www
  ansible.builtin.shell:
    executable: /bin/bash
    cmd: /usr/bin/npm install && /usr/bin/npm run build
    chdir: /usr/src/estuary-www
  become: true
  become_user: "{{ estuary_system_user | default('estuary') }}"

- name: Ensure estuary top directory exists
  ansible.builtin.file:
    path: /usr/estuary
    owner: "{{ estuary_system_user | default('estuary') }}"
    group: "{{ estuary_system_user | default('estuary') }}"
    mode: 0700
    state: directory
    recurse: false

- name: Ensure estuary private directory exists
  ansible.builtin.file:
    path: /usr/estuary/private
    owner: "{{ estuary_system_user | default('estuary') }}"
    group: "{{ estuary_system_user | default('estuary') }}"
    mode: 0700
    state: directory
    recurse: false

- name: Install Estuary token
  copy:
    src: secrets/token
    dest: /usr/estuary/private/token
    owner: "{{ estuary_system_user | default('estuary') }}"
    group: "{{ estuary_system_user | default('estuary') }}"
    mode: 0700

- name: Install Estuary WWW service
  template:
    src: estuary-www.service
    dest: /etc/systemd/system/estuary-www.service
    owner: root
    group: root
    mode: 0755

- name: Create config directory for estuary www
  ansible.builtin.file:
    path: /etc/estuary-www
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Copy main config
  ansible.builtin.template:
    src: config.env
    dest: /etc/estuary-www/config.env
    owner: root
    group: root
    mode: 0644

- name: Run daemon-reload
  ansible.builtin.command:
    cmd: systemctl daemon-reload

- name: Ensure estuary www is running
  ansible.builtin.systemd:
    name: estuary-www
    state: started
    enabled: true
